### ISSUE TITLE
App crashes after selecting date 

### ISSUE THREAD

**Issue by Nareshbathina** [bikasv/cordova-android-plugins#15]

**Comment by bikasv** [comment]
Can you please provide me the steps to reproduce and log/dump of any kind to investigate the issue? Also, give details about version of Cordova and Android you're testing on.

**Comment by Nareshbathina** [comment]
cordova version 5.3.3
android version 4.4.4
I have two fields textfield and date field
first select date from datepicker after that select textfield to enter text---crash

(try 3-4 times it will crash)

**Comment by Nareshbathina** [comment]
I think its due to memory leakage in my application  getting error "could not load texture for layer"

**Comment by bikasv** [comment]
Acknowledged
